### ISSUE TITLE
Platform error, installed from HACS

### ISSUE THREAD

**Issue by mobisat** [thecode/ha-rpi_gpio#132]
Platform error binary_sensor.rpi_gpio - Exception importing custom_components.rpi_gpio.binary_sensor

`binary_sensor:
  - platform: rpi_gpio
    host: 192.168.1.???
    sensors:
      - port: 17
        name: "Alarm Set"
      - port: 27
        name: "Alarm Activated"`

Any help woud be much appreciated

**Comment by thecode** [comment]
Please provide the full log after restart, it is impossible to understand from this what is wrong. Also add some information about your setup (OS, installation type)

**Comment by mobisat** [comment]
Looks like it is my fault. I used the old setup that was removed from HA to monitor the GPIO of a Pi on my LAN. From the log below it looks like your code only runs on a Pi for checking it's own GPIO. Unfortunately.


Home Assistant 2022.12.7 Supervisor 2022.11.2 Operating System 9.4 Frontend 20221213.1 - latest 

This error originated from a custom integration.

Logger: homeassistant.loader
Source: custom_components/rpi_gpio/__init__.py:3
Integration: rpi_gpio (documentation, issues)
First occurred: 20:01:15 (1 occurrences)
Last logged: 20:01:15

Unexpected exception importing platform custom_components.rpi_gpio.binary_sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 728, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 745, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/rpi_gpio/__init__.py", line 3, in <module>
    from RPi import GPIO  # pylint: disable=import-error
  File "/usr/local/lib/python3.10/site-packages/RPi/GPIO/__init__.py", line 23, in <module>
    from RPi._GPIO import *
RuntimeError: This module can only be run on a Raspberry Pi!

**Comment by thecode** [comment]
This is called "Home Assistant Raspberry Pi GPIO custom integration", it is used to help maintaining the one removed from core.
Thanks for reporting back, closing this issue 👍
