### ISSUE TITLE
RuntimeError: Conflicting edge detection already enabled for this GPIO channel

### ISSUE THREAD

**Issue by iancg** [thecode/ha-rpi_gpio#164]
I've upgraded to HA version 2023.3.5 which has a new feature of "Quick reload".

I have a simple gpio input pin

    - platform: rpi_gpio
      sensors:
        - port: 26
          name: Front Door Open

however after using the "Quick reload" feature (to pick up a change to a template), the sensor becomes unavailable.

Consulting the ha log, I found

    2023-03-17 11:10:08.268 ERROR (MainThread) [homeassistant.components.binary_sensor] Error while setting up rpi_gpio platform for binary_sensor
    Traceback (most recent call last):
      File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 293, in _async_setup_platform
        await asyncio.shield(task)
      File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
        result = self.fn(*self.args, **self.kwargs)
      File "/config/custom_components/rpi_gpio/binary_sensor.py", line 77, in setup_platform
        RPiGPIOBinarySensor(
      File "/config/custom_components/rpi_gpio/binary_sensor.py", line 132, in __init__
        edge_detect(self._port, edge_detected, self._bouncetime)
      File "/config/custom_components/rpi_gpio/__init__.py", line 59, in edge_detect
        GPIO.add_event_detect(port, GPIO.BOTH, callback=event_callback, bouncetime=bounce)
    RuntimeError: Conflicting edge detection already enabled for this GPIO channel

Performing a full restart on HA restores the sensor to correct behaviour.

One of the other components I use needed a fix for it to remain functional after a quick reload (see https://github.com/home-assistant/core/pull/89684 ).

**Comment by iancg** [comment]
I was already on the latest version and there is no newer version.  The issue still occurs.

**Comment by Serios** [comment]
I can confirm the issue! After YAML configuration reloading trough Developer Tools, the sensors are all unavailable. Doing a full restart on HA restores them.

**Comment by Patbonamy** [comment]
Hi,
I have the same issue.
HELP!!!
