### ISSUE TITLE
Raspberry Pi 5 Support

### ISSUE THREAD

**Issue by TroyJ** [thecode/ha-rpi_gpio#225]
ha-rpi_gpio is not working with Raspberry Pi 5.

2023-12-20 18:58:30.841 ERROR (MainThread) [homeassistant.components.switch] Error while setting up rpi_gpio platform for switch
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 361, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/rpi_gpio/switch.py", line 69, in setup_platform
    RPiGPIOSwitch(
  File "/config/custom_components/rpi_gpio/switch.py", line 100, in __init__
    setup_output(self._port)
  File "/config/custom_components/rpi_gpio/__init__.py", line 39, in setup_output
    GPIO.setup(port, GPIO.OUT)
RuntimeError: Cannot determine SOC peripheral base address
2023-12-20 19:00:33.540 WARNING (SyncWorker_10) [py.warnings] /config/custom_components/rpi_gpio/__init__.py:26: RuntimeWarning: No channels have been set up yet - nothing to clean up!  Try cleaning up at the end of your program instead!
  GPIO.cleanup()

Core
2024.1.0.dev20231218

Supervisor
2023.12.0

Operating System
11.3.dev20231214

Frontend
20231218.0.dev

**Comment by thecode** [comment]
You can  try https://codeberg.org/raboof/ha-gpio the author discussed here about adding support for Pi 5

**Comment by BorisHruby** [comment]
Today I tried to migrate my HA from RPi4 to RPi5. In the end I have managed it to work but the process was not so straightforward and easy as I was expecting at all. But what I wasn't able to make work was this integration.
I really don't know what could be the problem but it looks like it simply doesn't work on the RPi5 somehow...

![image](https://github.com/thecode/ha-rpi_gpio/assets/58848957/8fa3931a-fe6a-4527-a278-27d2fc0894b4)

**Comment by bsimmo** [comment]
Unless the integration is updated to use lgpio methods or similar it will
not work. The old Pi4 and before will not work as the Pi5 uses the RP1 for
GPIO now and uses the standard bookworm/linux methods.
There is a 'shim' that could be used as a halfway house.

**Comment by elik745i** [comment]
Same here, would want to use GPIO on RPI5 as several SSR relays hooked to my header to control garden lighting and power supplies.
