### ISSUE TITLE
rpi_gpio home assistant  not working 2024.3.1 on Raspberry pi 5

### ISSUE THREAD

**Issue by metju13** [thecode/ha-rpi_gpio#243]
After switching to Home Assistant on Raspberry Pi 5, GPIO management is no longer available. does anyone have any ideas on how to resolve this? Thank you

This entity is no longer provided by the rpi_gpio integration. If the entity is no longer used, delete it in settings.

Registratore: homeassistant.components.switch
Fonte: helpers/entity_platform.py:350
integration: Interruttore (documentazione, problemi)
Prima occorrenza: 09:15:54 (2 occorrenze)
Ultima registrazione: 09:17:40

Error while setting up rpi_gpio platform for switch
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 350, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/rpi_gpio/switch.py", line 69, in setup_platform
    RPiGPIOSwitch(
  File "/config/custom_components/rpi_gpio/switch.py", line 100, in __init__
    setup_output(self._port)
  File "/config/custom_components/rpi_gpio/__init__.py", line 39, in setup_output
    GPIO.setup(port, GPIO.OUT)
RuntimeError: Cannot determine SOC peripheral base address

**Comment by thecode** [comment]
Duplicate of https://github.com/thecode/ha-rpi_gpio/issues/225
