### ISSUE TITLE
HA 2024.12.0 errors

### ISSUE THREAD

**Issue by Zaleo80** [thecode/ha-rpi_gpio#331]
Looks like something broke after the 2024.12.0 update of Home Assistant (Core).

```
Error while setting up gpio platform for switch
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 366, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/gpio/switch.py", line 66, in setup_platform
    switches = [GPIOSwitch(switch[CONF_NAME],
                ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
                           switch[CONF_DEVICE],
                           ^^^^^^^^^^^^^^^^^^^^
                           switch[CONF_PORT],
                           ^^^^^^^^^^^^^^^^^^
                           switch[CONF_INVERT_LOGIC],
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^
                           switch.get(CONF_UNIQUE_ID))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/gpio/switch.py", line 89, in __init__
    self._line = setup_output(device, port)
                 ~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "/config/custom_components/gpio/__init__.py", line 69, in setup_output
    return _configure_line(
        device,
        port,
        direction=gpiod.line.Direction.OUTPUT)
  File "/config/custom_components/gpio/__init__.py", line 60, in _configure_line
    return gpiod.request_lines(
           ~~~~~~~~~~~~~~~~~~~^
        device,
        ^^^^^^^
        consumer=DOMAIN,
        ^^^^^^^^^^^^^^^^
        config={port: gpiod.LineSettings(**kwargs)})
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/gpiod/__init__.py", line 53, in request_lines
    with Chip(path) as chip:
         ~~~~^^^^^^
  File "/usr/local/lib/python3.13/site-packages/gpiod/chip.py", line 58, in __init__
    self._chip = _ext.Chip(path)
                 ~~~~~~~~~^^^^^^
FileNotFoundError: [Errno 2] No such file or directory
```

**Comment by tomer-w** [comment]
I just ran upgrade and didn't encounter any problem. Are you getting this constantly after restarts?

**Comment by Zaleo80** [comment]
Looks like the issue is HAOS 14, as also reported here:
https://github.com/jlinford/ha-gpio/issues/3

**Comment by tomer-w** [comment]
Can you send full logs include HA startup sequence?

**Comment by tomer-w** [comment]
As we didn't get any logs to investigate or being able to reproduce this, I will close the issue. Please re-open if this is still relevant with the required logs.
