### ISSUE TITLE
problem after upgrade of HA to 2022.6

### ISSUE THREAD

**Issue by homonto** [thecode/ha-rpi_gpio#64]
from configuration.yaml:
```
cover:
  - platform: rpi_gpio
    relay_time: 0.1
    invert_relay: false
    state_pull_mode: "UP"
    invert_state: true
    covers:
      - relay_pin: 17
        name: "ha esp32 reset"
```
from log:

```
Logger: homeassistant.components.cover
Source: custom_components/rpi_gpio/cover.py:75
Integration: Cover ([documentation](https://www.home-assistant.io/integrations/cover), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+cover%22))
First occurred: 21:32:12 (1 occurrences)
Last logged: 21:32:12

Error while setting up rpi_gpio platform for cover
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/rpi_gpio/cover.py", line 75, in setup_platform
    cover[CONF_STATE_PIN],
KeyError: 'state_pin'
```

**Comment by thecode** [comment]
Please share your YAML configuration for the covers

**Comment by homonto** [comment]
I have only 1 entry in the configuration.yaml - I posted on top of the previous post

**Comment by thecode** [comment]
Your configuration is missing the `state_pin`, looking at the history this key was always mandatory. Was this cover working in eailer home assistant versions? which one?

**Comment by homonto** [comment]
no more error - thank you
however I cannot check if that works - no physical connection between RPi and ESP - I think it was on my TODO list but wiring never happened ;-)

sorry for bothering you - thank you for your help

**Comment by homonto** [comment]
it is wired now (only 1 GPIO - relay_pin: 17 - state_pin not wired) and it works! ;-)
thank you
